/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class BookmarkTagSchema extends BaseModel {
  static $columns = ['id', 'bookmarkId', 'tagId', 'createdAt', 'updatedAt'] as const
  $columns = BookmarkTagSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare bookmarkId: number
  @column()
  declare tagId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BookmarkSchema extends BaseModel {
  static $columns = ['id', 'userId', 'title', 'url', 'favicon', 'description', 'viewCount', 'isPinned', 'isArchived', 'archivedAt', 'lastViewedAt', 'createdAt', 'updatedAt'] as const
  $columns = BookmarkSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number | null
  @column()
  declare title: string
  @column()
  declare url: string
  @column()
  declare favicon: string | null
  @column()
  declare description: string | null
  @column()
  declare viewCount: number
  @column()
  declare isPinned: boolean
  @column()
  declare isArchived: boolean
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column.dateTime()
  declare lastViewedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TagSchema extends BaseModel {
  static $columns = ['id', 'name', 'slug', 'userId', 'createdAt', 'updatedAt'] as const
  $columns = TagSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare userId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['id', 'fullName', 'email', 'password', 'createdAt', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare fullName: string | null
  @column()
  declare email: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
